FROM node:22-bookworm

ARG USERNAME=node

RUN apt-get update && apt-get install -y sudo\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}   

USER ${USERNAME}
WORKDIR /home/${USERNAME}/workspaces

# pnpmを有効化
ENV PNPM_HOME="/usr/local/share/pnpm"
ENV PNPM_CACHE="/usr/local/share/.pnpm-store"
ENV PATH="$PNPM_HOME:$PATH"
RUN sudo corepack enable \
    && sudo mkdir -p ${PNPM_HOME} && sudo chown -R $USERNAME ${PNPM_HOME} \
    && sudo mkdir -p ${PNPM_CACHE} && sudo chown -R $USERNAME ${PNPM_CACHE} \
    && pnpm config set store-dir /usr/local/share/.pnpm-store

# パッケージを導入
RUN pnpm add -g typescript @types/node ts-node @biomejs/biome @nestjs/cli \
    && pnpm dlx @biomejs/biome init
